name: EBAC CI

on:
  push: 
    branches: [ci]

  workflow_dispatch:
  
jobs:
  lest:
    runs-on: ubuntu-latest

  
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Cypress run
        uses: cypress-io/github-action@v3
        continue-on-error: true
        with:
          install-command: npm install
          broewser: chrome
      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
          
